//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodingIdeas.Core.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatableEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RatableEntity()
        {
            RatedEntities = new HashSet<RatedEntity>();
        }
    
        public Guid Id { get; set; }
        public Guid? UserId { get; set; }
        public DateTime PublishDate { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RatedEntity> RatedEntities { get; set; }
    }
}
