//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodingIdeas.Core.DB
{
    using System;

    public partial class RatedEntity
    {
        public Guid EntityId { get; set; }
        public Guid UserId { get; set; }
        public short Rating { get; set; }
    
        public virtual RatableEntity RatableEntity { get; set; }
        public virtual User User { get; set; }
    }
}
