//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodingIdeas.Core.DB
{
    using System;

    partial class UserSkill
    {
        public Guid UserId { get; set; }
        public Guid ProgrammingLanguageId { get; set; }
        public short Proficiency { get; set; }
    
        public virtual ProgrammingLanguage ProgrammingLanguage { get; set; }
        public virtual User User { get; set; }
    }
}
